### ISSUE TITLE
Error when truncating a table that is externally referenced from another table by specifying the table name.

### ISSUE THREAD

**Issue by shunji-onodera** [cloudspannerecosystem/spanner-truncate#14] opened 2023-08-24 03:51 UTC
Thank you for the great tool.
We use it all the time.

When I try to truncate a table that is externally referenced from another table by specifying the table name, I seem to get an invalid memory address or nil pointer dereference.

We think this is the relevant area.
https://github.com/cloudspannerecosystem/spanner-truncate/blob/main/truncate/coordinator.go#L116-L141

If a foreign key reference is set up with a column name different from the table name, It seems that even though the tableMap is registered with schema.tableName, it is referenced by tableMap[referencing] when it is referenced, resulting in a nil reference and a segmentation fault.

For example, this occurs when there is another table that references the "User" table with the column name "ReferenceUserId".

It looks like the only way to get around this is to use the referencing column name in the form tableName+Id.
Is there any other way around this?

**Comment by yfuruyama** [comment] 2023-08-25 10:20
@shunji-onodera Thank you for filing the issue and apologies for my late response.

To better understand the issue, could you share the example table schema and the spanner-truncate command that can reproduce this issue?

**Comment by shunji-onodera** [comment] 2023-08-28 12:07
@yfuruyama 

Prepare data for a table schema like this.
```
CREATE TABLE Users (
  UserId STRING(36) NOT NULL,
  AccountId STRING(36),
  UpdatedAt TIMESTAMP NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
) PRIMARY KEY(UserId);

CREATE TABLE Test (
    TestId STRING(36) NOT NULL,
    TestName STRING(255) NOT NULL,
    Object STRING(255) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
) PRIMARY KEY(TestId);

CREATE TABLE UserTest (
	TestId STRING(36) NOT NULL,
	TesterUserId STRING(36) NOT NULL,
	CONSTRAINT FKTesterUserId FOREIGN KEY (TesterUserId) REFERENCES Users (UserId)
) PRIMARY KEY(TestId, TesterUserId),
INTERLEAVE IN PARENT Test ON DELETE CASCADE;
```


The DML looks like this.
```
INSERT INTO Users (UserId, AccountId, UpdatedAt, CreatedAt) VALUES
('a1b2-c3d4-e5f6-g7h8-i9j0', 'acc1-1234-5678-9101-1121', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO Test (TestId, TestName, Object, CreatedAt, UpdatedAt) VALUES
('1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p', 'Test1', 'Object1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO UserTest (TestId, TesterUserId) VALUES
('1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p', 'a1b2-c3d4-e5f6-g7h8-i9j0');
```

We used it as such a library in our unit testing with DB.
```
err := truncate.Run(
		ctx,
		{{ project_id }},
		{{ instance_name }},
		{{ database_name }},
		true,
		new(bytes.Buffer),
		[]string{"Users"}, // <---
		[]string{},
	)
```
Make Users the target of truncate, delete the data, then put the data into Users and run the test.
The Test and UserTest tables do nothing.

Then it seems to result in this error.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xfd5429]

goroutine 1026 [running]:
github.com/cloudspannerecosystem/spanner-truncate/truncate.(*table).isDeletable(0xc00013cf50)
	/go/pkg/mod/github.com/cloudspannerecosystem/spanner-truncate@v0.1.0/truncate/coordinator.go:54 +0xc9
github.com/cloudspannerecosystem/spanner-truncate/truncate.findDeletableTables({0xc0005ec600, 0x1, 0xc0001aa000?})
	/go/pkg/mod/github.com/cloudspannerecosystem/spanner-truncate@v0.1.0/truncate/coordinator.go:92 +0x8d
github.com/cloudspannerecosystem/spanner-truncate/truncate.(*coordinator).start.func1()
	/go/pkg/mod/github.com/cloudspannerecosystem/spanner-truncate@v0.1.0/truncate/coordinator.go:184 +0x16a
created by github.com/cloudspannerecosystem/spanner-truncate/truncate.(*coordinator).start
	/go/pkg/mod/github.com/cloudspannerecosystem/spanner-truncate@v0.1.0/truncate/coordinator.go:175 +0x95
```

It seems to happen only when the table names are specified in the eighth argument targetTables of truncate.Run.
You can avoid this by specifying an empty slice and executing on all tables.

**Comment by yfuruyama** [comment] 2023-08-30 00:03
@shunji-onodera Thank you so much for sharing the details. I'll check it and get back to you.

**Comment by yfuruyama** [comment] 2023-09-01 13:07
@shunji-onodera It looks like this is the validation error of spanner-truncate.

In your example, only `Users` table was specified in the `truncate.Run` function, but `Users` table is referenced by `UserTest` table, so  to delete `Users` table,`UserTest` table must be specified as well. Otherwise, the deletion will be failed due to [referential integrity error](https://cloud.google.com/spanner/docs/foreign-keys/overview#what-are-foreign-keys).

This should be fixed, but in the meantime, please specify both `Users` and `UserTest` tables when running truncate.

**Comment by shunji-onodera** [comment] 2023-09-01 13:42
@yfuruyama Thank you for your research!
We are eagerly awaiting update! 🙏 😂

**Closed as completed** 2023-09-04 00:06 UTC

**Comment by yfuruyama** [comment] 2023-09-04 00:09
@shunji-onodera I fixed the validation logic and now it returns an error if the referencing table is not included in the target table list. For next run, please include `UserTest` table in the argument for `truncate.Run`.

The new tag is available: https://github.com/cloudspannerecosystem/spanner-truncate/releases/tag/v0.1.1

**Comment by shunji-onodera** [comment] 2023-09-04 01:33
@yfuruyama Thank you very much! 👍
